config/routes.rb
Practice::Application.routes.draw do

  root 'users#index'

  resources :users do
    get 'perverts', on: :collection
  	get 'love', on: :member

    resources :posts do
      get 'perverts', on: :collection
      get 'stalin', on: :member
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
   validates :name, presence: true
   validates_length_of :name, :minimum =>2

  class << self

    def big (user) 
      user.capitalize!
    end

    def sir (user)
       user.prepend 'Sir, '
      
    end 
    
  end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :load_parent

  def perverts
     @posts = @user.posts.all
  end

  def stalin
    @post = @user.posts.find(params[:id])
  end
  
  def index
    @posts = @user.posts.all
  end

  def show
    @post = @user.posts.find(params[:id])
  end

  def new
    @post = @user.posts.new
  end

  def edit
    @post = @user.posts.find(params[:id])
  end
  
  def create
    @post = @user.posts.new(params[:post].permit(:content, :user_id))

    respond_to do |format|
      if @post.save
        format.html { redirect_to [@user, @post], notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @post = @user.posts.find(params[:id])

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to [@user, @post], notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = @user.posts.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to user_posts_path(@user) }
      format.json { head :no_content }
    end
  end

  private

    def load_parent
      @user = User.find(params[:user_id])
    end
 
    def post_params
      params.require(:post).permit(:content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :love]

  def perverts
     @users = User.all
  end

  def love
  end

  def index
    @users = User.all
  end


  def show
    User.sir(User.big(@user.name))

  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def time_now
   Time.now.strftime("%H:%M")
  end

  def quantity_users
    quantity = @users.length
  end 

  def quantity_posts_posts
    quantity = @user.posts.count
  end
   def quantity_posts (user)
    quantity = user.posts.count
  end 
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> Practice </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.slim
doctype
html
  head
    title Practice
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body

    .navbar.navbar-inverse.navbar-fixed-top role="navigation"
      .container
        .navbar-header
          a.navbar-brand href="/" Forum
        .collapse.navbar-collapse
          ul.nav.navbar-nav
            li
              a href="/" Home
            li
              = link_to 'New User', new_user_path
          .rr
            #{time_now} 

    
    br
      br
        br
          br
            .container
              .starter-template
                p.lead= yield
            /! /.container

    .btn_test
      input type="button" value='run_test'

    .test

    
    .one
      = image_tag("one.png") 

    .two
      = image_tag("two.png") 

    .mine
      = image_tag("mine.png")

    br
    br
    br
    

    .footer
      | Contact us: example@gmail.ua
              


           

app/views/posts/_form.html.erb
<%= form_for([@user, @post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_form.html.slim
= form_for([@user, @post]) do |f|
  - if @post.errors.any?
    #error_explanation
      h2
        = pluralize(@post.errors.count, "error")
        | prohibited this post from being saved:
      ul
        - @post.errors.full_messages.each do |msg|
          li= msg
  .field
    = f.label :content
    br
      = f.text_field :content 
    br
  .actions
    = f.submit class: "btn btn-warning"
  br

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', user_post_path(@user, @post) %> |
<%= link_to 'Back', user_posts_path(@user) %>

app/views/posts/edit.html.slim
h1 Editing post
.well
  = render 'form'
  button.btn.btn-info type="button" = link_to 'Show', user_post_path(@user, @post)
  | &nbsp
  button.btn.btn-succes type="button" = link_to 'Back', user_posts_path(@user)

app/views/posts/index.html.erb
<h1>List of posts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td><%= post.user_id %></td>
        <td><%= link_to 'Show', user_post_path(@user, post) %> </td>
        <td><%= link_to 'Edit', edit_user_post_path(@user, post) %></td>
        <td><%= link_to 'Destroy',[@user, post], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Post', new_user_post_path(@user) %> |
<%= link_to 'Doubtful Posts', perverts_user_posts_path(@user) %> |
<%= link_to 'Back to users', users_path(@user) %> |

<h4> Amount of posts <%= quantity_posts %> </h4>

<h5> Current time <%= time_now %> </h5>

app/views/posts/index.html.slim
h1 List of posts
.well
  table
    thead
      tr
        td 
          h2 Content &nbsp
        
        td
        td
        td
    tbody
      - @posts.each do |post|
        tr
          td 
            h3 = post.content
          
          td
             button.btn.btn-info type="button" = link_to 'Show', user_post_path(@user, post)
          td
            button.btn.btn-warning type="button" = link_to 'Edit', edit_user_post_path(@user, post)
          td
            button.btn.btn-danger type="button"= link_to 'Destroy',[@user, post], method: :delete, data:   {confirm: 'Are you sure?'}
  h5
      | Total:#{quantity_posts_posts}
  br
    button.btn.btn-primary type="button" = link_to 'New Post', new_user_post_path(@user)
    | &nbsp
    button.btn.btn-default type="button" = link_to 'Doubtful Posts', perverts_user_posts_path(@user)
    | &nbsp
    button.btn.btn-succes type="button" = link_to 'Back to users', users_path(@user)
    
 

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', user_posts_path(@user) %>

app/views/posts/new.html.slim
h1 New post
.well
  = render 'form'
  button.btn.btn-succes type="button" = link_to 'Back', user_posts_path(@user)

app/views/posts/perverts.html.erb
<h1>Doubtful posts</h1>

<table>
  <thead>
    <tr>
      <th>Posts</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <%  if post.content == "sheep" %>
        <td><%= post.content %></td>
        <td><%= post.user_id %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back', user_posts_path %>

app/views/posts/perverts.html.slim
h1 Doubtful posts
.well
  table
    thead
      tr
        td 
        h2 Posts
        
    tbody
      - @posts.each do |post|
        tr
          - if post.content == "sheep"
            td
            h3 = post.content
          
br
  button.btn.btn-succes type="button" = link_to 'Back', user_posts_path

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<h2><%= link_to 'Had you seen Stalin?', stalin_user_post_path(@user, @post) %>  </h2>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_user_post_path(@user, @post) %> |
<%= link_to 'Back', user_posts_path(@user) %>

app/views/posts/show.html.slim
button.btn.btn-default type="button" = link_to 'Had you seen Stalin?', stalin_user_post_path(@user, @post)
.well
  p#notice= notice
    
  p
    h3 Content:
    h4 = @post.content

  button.btn.btn-warning type="button" = link_to 'Edit', edit_user_post_path(@user, @post)
  | &nbsp
  button.btn.btn-succes type="button"= link_to 'Back', user_posts_path(@user)

app/views/posts/stalin.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1>Content:</h1>
 <h2> <%= @post.content %><h2>
</p>

<p>
  <h1>User:</h1>
  <h2><%= @post.user_id %></h2>
</p>


<%= link_to 'Back', user_posts_path(@user) %>

app/views/posts/stalin.html.slim
p#notice= notice
.well
  p
    h1 Content:
    h2
      = @post.content
      h2
  p
    h1 User:
    h2= @post.user_id
  button.btn.btn-succes type="button" = link_to 'Back', user_posts_path(@user)

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_form.html.slim
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      h2
        = pluralize(@user.errors.count, "error")
        | prohibited this user from being saved:
      ul
        - @user.errors.full_messages.each do |msg|
          li= msg
  .field
    = f.label :name
    br
      = f.text_field :name
    br
  .actions
    = f.submit class: "btn btn-warning"
br

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/edit.html.slim
h1 Editing user
.well
  = render 'form'
  button.btn.btn-info type="button" = link_to 'Show', @user 
  | &nbsp
  button.btn.btn-succes type="button" = link_to 'Back', users_path

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %> |
<%= link_to 'Show perverts', perverts_users_path %> |

<h4> Amount of users <%= quantity_users %> </h4>

<h5> Current time <%= time_now %> </h5>

app/views/users/index.html.slim
h1 List of users
.well
  table
    thead
      tr
        td
          h2
            |Name
        td
          
        td
        td
    tbody
      - @users.each do |user|
        tr
          td 
            h2 = user.name
          td 
            span.badge = quantity_posts(user)
            | &nbsp
            | &nbsp
            | &nbsp
            | &nbsp
          td 
            button.btn.btn-info type="button" = link_to 'Show', user 
          td
            button.btn.btn-warning type="button" = link_to 'Edit', edit_user_path(user)
          td 
            button.btn.btn-danger type="button" = link_to 'Destroy', user, method: :delete, data:   {confirm: 'Are you sure?'}
  h5
      | Total:#{quantity_users} 
  br
    button.btn.btn-primary type="button" = link_to 'New User', new_user_path
    | &nbsp
    button.btn.btn-default type="button" = link_to 'Show perverts', perverts_users_path
    
  

app/views/users/love.html.erb
<%  if @user.name == "abdul" %>
  <%= image_tag("sheep.jpg") %>
  <%else%>
  <%= image_tag("girl.jpg") %>
<%end%>
<%= link_to 'Back', users_path %> 

app/views/users/love.html.slim
- if @user.name == "abdul"
  .img-rounded
    = image_tag("sheep.jpg")
- else
  .img-rounded
    = image_tag("girl.jpg") 
  
| &nbsp
button.btn.btn-succes type="button" = link_to 'Back', users_path

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/new.html.slim
h2 New user
.well
  = render 'form'
  br
  button.btn.btn-succes type="button" = link_to 'Back', users_path

app/views/users/perverts.html.erb
<h1>List of perverts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <%  if user.name == "abdul" %>
        <td><%= user.name %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back', root_path %>

app/views/users/perverts.html.slim
h2 List of perverts
.well
  table
    thead
      tr
        td 
          h3 Name
        td
        td
        td
    tbody
      - @users.each do |user|
        tr
          - if user.name == "abdul"
            td
              h4 = user.name
  br
    button.btn.btn-succes type="button" = link_to 'Back', users_path

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> |
<%= link_to 'Posts', user_posts_path(@user) %> |
<%= link_to 'Love', love_user_path %> 

app/views/users/show.html.slim
.well 
  p#notice= notice
  p
    h2 Name
    h3 = @user.name
  button.btn.btn-warning type="button" = link_to 'Edit', edit_user_path(@user)
  | &nbsp
  button.btn.btn-succes type="button" = link_to 'Back', users_path
  | &nbsp
  button.btn.btn-primary type="button" = link_to 'Posts', user_posts_path(@user)
  | &nbsp
  button.btn.btn-default type="button" = link_to 'Prefers', love_user_path